dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "rule-set:fake_ip_filter_juewuy"
    # - "*"
    # - +.lan
    # - +.local
    # - time.*.com
    # - ntp.*.com
    # - +.market.xiaomi.com
  use-hosts: false
  use-system-hosts: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
    - system
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.alidns.com/dns-query      # é˜¿é‡Œï¼ˆå›½å†…ç¨³å®šï¼‰
    - https://doh.pub/dns-query             # è…¾è®¯ (å¢ƒå†…ï¼ŒDoHï¼Œå¯ä½œä¸ºå¤‡é€‰)      
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query     # Cloudflareï¼ŒDoH3
    - https://dns.google/dns-query  # Googleï¼ŒDoH3
    - 1.1.1.1
    - 8.8.8.8
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 1.1.1.1 # Cloudflare DNSå¤‡ç”¨
    - 8.8.8.8 # Google DNSå¤‡ç”¨
  respect-rules: true
  prefer-h3: true      # å¦‚æœDNSæœåŠ¡å™¨æ”¯æŒDoH3ä¼šä¼˜å…ˆä½¿ç”¨h3ï¼Œæå‡æ€§èƒ½
  cache-algorithm: arc # ä½¿ç”¨æ€§èƒ½æ›´ä¼˜çš„ ARC ç¼“å­˜ç®—æ³•
  cache-size: 2048     # é™åˆ¶ç¼“å­˜å¤§å°ï¼Œé¿å…å ç”¨è¿‡å¤šå†…å­˜

proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
    include-all: true
    type: select
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    include-all: true
    exclude-filter: (?i)\[\d+(?:x)?\]
    interval: 300
    tolerance: 50
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    include-all: true
    filter: (?i)æ¸¯|HK|hk|Hong Kong|HongKong|hongkong
    exclude-filter: (?i)\[\d+(?:x)?\]
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    include-all: true
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore
    exclude-filter: (?i)\[\d+(?:x)?\]
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    include-all: true
    filter: (?i)ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States
    exclude-filter: (?i)\[\d+(?:x)?\]
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    include-all: true
    filter: (?i)æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan
    exclude-filter: (?i)\[\d+(?:x)?\]
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    include-all: true
    filter: (?i)å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan
    exclude-filter: (?i)\[\d+(?:x)?\]
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    include-all: true
    filter: (?i)KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“
    exclude-filter: (?i)\[\d+(?:x)?\]
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ’µ å€ç‡èŠ‚ç‚¹
    include-all: true
    filter: (?i)\[\d+(?:x)?\]
    type: select
  - name: ğŸŒ å…¶ä»–åœ°åŒº
    include-all: true
    exclude-filter: (?i)\[\d+(?:x)?\]|æ¸¯|HK|Hong.?Kong|hongkong|å°|TW|Taiwan|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|JP|Japan|ç¾|æ´›æ‰çŸ¶|ç¡…è°·|è¥¿é›…å›¾|èŠåŠ å“¥|US|United.?States|KR|Korea|é¦–å°”|éŸ©|éŸ“
    type: select
  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ’¬ OpenAi
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ“¹ æ²¹ç®¡è§†é¢‘
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ“º å“”å“©å“”å“©
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  - name: ğŸ“° å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ“° å›½å†…åª’ä½“
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  - name: â“‚ï¸ å¾®è½¯Bing
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  - name: â“‚ï¸ å¾®è½¯äº‘ç›˜
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - ğŸ’µ å€ç‡èŠ‚ç‚¹
      - ğŸ”ï¸ æ‰‹åŠ¨åˆ‡æ¢
  

rule-providers:
  LocalAreaNetwork:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  UnBan:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
    path: ./ruleset/UnBan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanAD:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanProgramAD:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleFCM:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleFCM.list
    path: ./ruleset/GoogleFCM.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleCN:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SteamCN:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/SteamCN.list
    path: ./ruleset/SteamCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bing:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Bing.list
    path: ./ruleset/Bing.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OneDrive:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list
    path: ./ruleset/OneDrive.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Microsoft:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
    path: ./ruleset/Microsoft.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Apple:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
    path: ./ruleset/Apple.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Telegram:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OpenAi:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Epic:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Epic.list
    path: ./ruleset/Epic.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Origin:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Origin.list
    path: ./ruleset/Origin.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Sony:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Sony.list
    path: ./ruleset/Sony.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Steam:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Steam.list
    path: ./ruleset/Steam.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Nintendo:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Nintendo.list
    path: ./ruleset/Nintendo.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  YouTube:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BilibiliHMT:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BilibiliHMT.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bilibili:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Bilibili.list
    path: ./ruleset/Bilibili.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMedia:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaMedia.list
    path: ./ruleset/ChinaMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyMedia:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFWlist:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaDomain:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
    behavior: domain
    interval: 86400
    format: text
    type: http
  ChinaCompanyIp:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
    behavior: ipcidr
    interval: 86400
    format: text
    type: http
  Download:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
    path: ./ruleset/Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  myDirect:
    type: http
    behavior: classical
    format: text
    url: "https://gh-proxy.com/https://github.com/MaxZH42/PersonnelConfig/blob/main/ruleProviders/direct.list"
    path: ./ruleset/myDirect.list
    interval: 86400 
  myReject:
    type: http
    behavior: classical
    format: text
    url: "https://gh-proxy.com/https://github.com/MaxZH42/PersonnelConfig/blob/main/ruleProviders/reject.list"
    path: ./ruleset/myReject.list
    interval: 86400
  myProxy:
    type: http
    behavior: classical
    format: text
    url: "https://gh-proxy.com/https://github.com/MaxZH42/PersonnelConfig/blob/main/ruleProviders/proxy.list"
    path: ./ruleset/myProxy.list
    interval: 86400
  myProxySG:
    type: http
    behavior: classical
    format: text
    url: "https://gh-proxy.com/https://github.com/MaxZH42/PersonnelConfig/blob/main/ruleProviders/proxySG.list"
    path: ./ruleset/myProxySG.list
    interval: 86400
  myProxyHK:
    type: http
    behavior: classical
    format: text
    url: "https://gh-proxy.com/https://github.com/MaxZH42/PersonnelConfig/blob/main/ruleProviders/proxyHK.list"
    path: ./ruleset/myProxyHK.list
    interval: 86400
  fake_ip_filter_juewuy:
    type: http
    behavior: classical
    format: text
    path: ./ruleset/fake_ip_filter_juewuy.list,
    url: "https://gh-proxy.com/https://raw.githubusercontent.com/juewuy/ShellCrash/refs/heads/dev/public/fake_ip_filter.list"
    interval: 86400

rules:
  - "RULE-SET,myDirect,DIRECT"
  - "RULE-SET,myProxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,myReject,REJECT"
  - "RULE-SET,myProxySG,ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹"
  - "RULE-SET,myProxyHK,ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
  - "RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,BanAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
  - "RULE-SET,BanProgramAD,ğŸƒ åº”ç”¨å‡€åŒ–"
  - "RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM"
  - "RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,Bing,â“‚ï¸ å¾®è½¯Bing"
  - "RULE-SET,OneDrive,â“‚ï¸ å¾®è½¯äº‘ç›˜"
  - "RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡"
  - "RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡"
  - "RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
  - "RULE-SET,OpenAi,ğŸ’¬ OpenAi"
  - "RULE-SET,Epic,ğŸ® æ¸¸æˆå¹³å°"
  - "RULE-SET,Origin,ğŸ® æ¸¸æˆå¹³å°"
  - "RULE-SET,Sony,ğŸ® æ¸¸æˆå¹³å°"
  - "RULE-SET,Steam,ğŸ® æ¸¸æˆå¹³å°"
  - "RULE-SET,Nintendo,ğŸ® æ¸¸æˆå¹³å°"
  - "RULE-SET,YouTube,ğŸ“¹ æ²¹ç®¡è§†é¢‘"
  - "RULE-SET,BilibiliHMT,ğŸ“º å“”å“©å“”å“©"
  - "RULE-SET,Bilibili,ğŸ“º å“”å“©å“”å“©"
  - "RULE-SET,ChinaMedia,ğŸ“° å›½å†…åª’ä½“"
  - "RULE-SET,ProxyMedia,ğŸ“° å›½å¤–åª’ä½“"
  - "RULE-SET,ProxyGFWlist,ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,Download,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿"
  - "MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼"
